"""Streamlit demo app for the trained NSL-KDD two-stage IDS model.

Run after training:
    streamlit run app.py
"""

from __future__ import annotations

import io
from pathlib import Path

import pandas as pd
import streamlit as st

from src.nids.config import NSL_KDD_COLUMNS
from src.nids.data import add_targets, feature_frame
from src.nids.modeling import load_artifacts


BASE_DIR = Path(__file__).resolve().parent
ARTIFACT_PATH = BASE_DIR / "artifacts" / "ids_artifacts.joblib"


def normalize_uploaded_columns(raw: pd.DataFrame) -> pd.DataFrame:
    """Normalize a raw NSL-KDD-style DataFrame to the standard column schema."""
    if raw.shape[1] == 41:
        raw.columns = NSL_KDD_COLUMNS[:-2]
        raw["label"] = "unknown"
        raw["difficulty"] = 0
    elif raw.shape[1] == 42:
        raw.columns = NSL_KDD_COLUMNS[:-1]
        raw["difficulty"] = 0
    elif raw.shape[1] == 43:
        raw.columns = NSL_KDD_COLUMNS
    else:
        raise ValueError(
            f"Expected 41, 42, or 43 columns, but found {raw.shape[1]} columns. "
            "Please upload an NSL-KDD-style .txt or .csv file."
        )
    raw["label"] = raw["label"].astype(str).str.strip().str.rstrip(".")
    return raw


def load_uploaded_file(uploaded_file) -> pd.DataFrame:
    """Read a NSL-KDD-style uploaded text/CSV file without leaving temp files."""
    raw = pd.read_csv(io.BytesIO(uploaded_file.getvalue()), header=None)
    return add_targets(normalize_uploaded_columns(raw))


def predict_two_stage(df: pd.DataFrame, artifacts: dict) -> pd.DataFrame:
    """Run the two-stage IDS prediction pipeline on a prepared DataFrame."""
    X = feature_frame(df)
    binary_model = artifacts["binary_model"]
    family_model = artifacts["attack_family_model"]

    binary_pred = binary_model.predict(X)
    binary_prob = None
    if hasattr(binary_model, "predict_proba"):
        proba = binary_model.predict_proba(X)
        if proba.shape[1] >= 2:
            binary_prob = proba[:, 1]

    out = df.copy()
    out["pred_binary"] = binary_pred
    out["pred_binary_label"] = ["attack" if x == 1 else "normal" for x in binary_pred]
    out["attack_probability"] = binary_prob if binary_prob is not None else pd.NA
    out["pred_final_label"] = "normal"

    attack_idx = out.index[out["pred_binary"] == 1]
    if len(attack_idx) > 0:
        out.loc[attack_idx, "pred_final_label"] = family_model.predict(
            feature_frame(out.loc[attack_idx])
        )

    return out


def main() -> None:
    st.set_page_config(page_title="Network Intrusion Detection Demo", layout="wide")
    st.title("Multi-Stage Machine Learning Framework for Network Intrusion Detection")
    st.write(
        "Upload an NSL-KDD style traffic file. The app first predicts normal vs attack, "
        "then classifies attacks into DoS, Probe, R2L, or U2R."
    )

    if not ARTIFACT_PATH.exists():
        st.error(
            "Model artifacts were not found. Run `python train_pipeline.py` first, "
            "or keep the included quick-run artifact in artifacts/ids_artifacts.joblib."
        )
        st.stop()

    artifacts = load_artifacts(ARTIFACT_PATH)
    st.sidebar.success(f"Loaded model: {artifacts.get('best_binary_model_name', 'unknown')}")
    st.sidebar.caption("Only load .joblib artifacts generated by this project or another trusted source.")

    uploaded = st.file_uploader("Upload NSL-KDD .txt or .csv file", type=["txt", "csv"])
    if uploaded is None:
        st.info("Try uploading `data/KDDTest+.txt` after training.")
        return

    try:
        df = load_uploaded_file(uploaded)
        preds = predict_two_stage(df, artifacts)
    except Exception as exc:  # pragma: no cover - Streamlit display path
        st.error(f"Could not process file: {exc}")
        return

    st.subheader("Prediction Summary")
    c1, c2, c3 = st.columns(3)
    c1.metric("Rows", f"{len(preds):,}")
    c2.metric("Predicted attacks", f"{int((preds['pred_binary'] == 1).sum()):,}")
    c3.metric("Predicted normal", f"{int((preds['pred_binary'] == 0).sum()):,}")

    st.bar_chart(preds["pred_final_label"].value_counts())

    show_cols = ["pred_binary_label", "pred_final_label", "attack_probability"]
    if "label" in preds.columns:
        show_cols = ["label", "final_target"] + show_cols
    st.subheader("First 100 Predictions")
    st.dataframe(preds[show_cols].head(100), use_container_width=True)

    st.download_button(
        "Download predictions as CSV",
        preds.to_csv(index=False).encode("utf-8"),
        file_name="ids_predictions.csv",
        mime="text/csv",
    )


if __name__ == "__main__":
    main()
